export const patientsList = [
  {
    name: 'Olivia Brown',
    mrNumber: 'TYU12345678',
    gender: 'Female',
    accession: '456RND',
    doctor: 'Emily Chen',
    notes: 'Completed',
    result: 'Released',
    status: 'Completed',
  },
  {
    name: 'Ethan Lee',
    mrNumber: 'GHN98765432',
    gender: 'Male',
    accession: '789RND',
    doctor: 'Liam Kim',
    notes: 'Pending',
    result: 'N/A',
    status: 'Pending',
  },
  {
    name: 'Ava Patel',
    mrNumber: 'JKL45678901',
    gender: 'Female',
    accession: '234RND',
    doctor: 'Noah Taylor',
    notes: 'Completed',
    result: 'Released',
    status: 'Completed',
  },
  {
    name: 'Liam Hall',
    mrNumber: 'POI98765432',
    gender: 'Male',
    accession: '567RND',
    doctor: 'Sophia Rodriguez',
    notes: 'Pending',
    result: 'N/A',
    status: 'Pending',
  },
  {
    name: 'Sophia Martin',
    mrNumber: 'MNB45678901',
    gender: 'Female',
    accession: '890RND',
    doctor: 'Mason Davis',
    notes: 'Completed',
    result: 'Released',
    status: 'Completed',
  },
  {
    name: 'Noah Brooks',
    mrNumber: 'RST12345678',
    gender: 'Male',
    accession: '345RND',
    doctor: 'Isabella Garcia',
    notes: 'Pending',
    result: 'N/A',
    status: 'Pending',
  },
  {
    name: 'Isabella White',
    mrNumber: 'FGH98765432',
    gender: 'Female',
    accession: '678RND',
    doctor: 'Alexander Brown',
    notes: 'Completed',
    result: 'Released',
    status: 'Completed',
  },
  {
    name: 'Alexander Thompson',
    mrNumber: 'CVB45678901',
    gender: 'Male',
    accession: '901RND',
    doctor: 'Charlotte Lee',
    notes: 'Pending',
    result: 'N/A',
    status: 'Pending',
  },
  {
    name: 'Charlotte Taylor',
    mrNumber: 'BNM12345678',
    gender: 'Female',
    accession: '234RND',
    doctor: 'Benjamin Hall',
    notes: 'Completed',
    result: 'Released',
    status: 'Completed',
  },
  {
    name: 'Benjamin Martin',
    mrNumber: 'POI98765432',
    gender: 'Male',
    accession: '567RND',
    doctor: 'Abigail Patel',
    notes: 'Pending',
    result: 'N/A',
    status: 'Pending',
  }
];